[package]
name = "clearhead-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
tree-sitter = { version = "*" }
tree-sitter-actions = { version = "*" }
autosurgeon = { version = "*" }
ratatui = { version = "*" }
chrono = { version = "*" }
rrule = { version = "*" }
config = { version = "*" }
directories = { version = "5.0.0" }
toml = { version = "*", features = ["display"] }
serde = { version = "*" }
