//! Telemetry module for semantic event logging.
//!
//! This module implements the observability specification for ClearHead tooling,
//! providing semantic event logging for debugging, analytics, and audit trails.
//!
//! # Overview
//!
//! Events are stored as newline-delimited JSON (NDJSON) in XDG state directory:
//! - **Linux/macOS:** `~/.local/state/clearhead/telemetry/events-YYYY-MM.ndjson`
//! - **Windows:** `%LOCALAPPDATA%\clearhead\state\telemetry\events-YYYY-MM.ndjson`
//!
//! Files rotate monthly by default for easy archival and querying.
//!
//! # Event Categories
//!
//! - **Action Lifecycle:** created, completed, cancelled, started, blocked, restarted, deleted
//! - **Property Changes:** priority_changed, due_date_changed, name_changed, context_added/removed
//! - **Recurring Actions:** instance_generated, instance_completed, instance_skipped, template_edited
//! - **Sync Operations:** sync_started, sync_completed, sync_failed, conflict_resolved
//! - **System Events:** workspace_opened, file_parsed, lsp_started
//!
//! # Usage
//!
//! ```rust,ignore
//! use clearhead_cli::telemetry::{emit_event, TelemetryEvent, Tool};
//!
//! // Emit an event with the current timestamp
//! emit_event(
//!     Tool::Cli,
//!     Some("action-uuid".to_string()),
//!     TelemetryEvent::ActionCreated {
//!         name: "My task".to_string(),
//!         file_path: "inbox.actions".to_string(),
//!     },
//! )?;
//! ```
//!
//! # Output Format
//!
//! Each line in the NDJSON file is a complete JSON object:
//!
//! ```json
//! {"timestamp":"2026-01-30T10:30:00+00:00","tool":"cli","action_uuid":"...","event":"action_created","name":"...","file_path":"..."}
//! ```
//!
//! Events can be queried with standard tools like DuckDB or jq:
//!
//! ```bash
//! # Count events by type
//! jq -s 'group_by(.event) | map({event: .[0].event, count: length})' events-2026-01.ndjson
//!
//! # Find all completions for an action
//! jq 'select(.action_uuid == "abc-123" and .event == "action_completed")' events-2026-01.ndjson
//! ```
//!
//! # Relationship to Other Concerns
//!
//! - **CRDT (Automerge):** Handles coordination and conflict resolution
//! - **Domain Files (.actions):** Human-readable state, queryable
//! - **Telemetry (this module):** Debugging, analytics, audit trail
//!
//! These are complementary. CRDT tracks *operational* history (insertions, deletions).
//! Telemetry tracks *semantic* history (what those operations meant in domain terms).

use chrono::{DateTime, Utc};
use serde::Serialize;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::PathBuf;
use tracing::info;

use clearhead_core::diff::FieldChange;
use clearhead_core::ActionState;

/// Tool identifier indicating the source of an event.
///
/// This helps distinguish events generated by different ClearHead tools
/// when analyzing telemetry data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Tool {
    /// Command-line interface
    Cli,
    /// Language Server Protocol implementation
    Lsp,
    /// Sync daemon or operation
    Sync,
}

/// Semantic events as defined in the observability specification.
///
/// Each variant corresponds to a meaningful domain event that provides
/// value for debugging, analytics, or audit purposes.
///
/// Events are serialized with a `"event"` field containing the snake_case event name.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "event")]
pub enum TelemetryEvent {
    // =========================================================================
    // Action Lifecycle Events
    // =========================================================================
    /// A new action was created.
    #[serde(rename = "action_created")]
    ActionCreated {
        /// Name of the created action
        name: String,
        /// Path to the file containing the action
        file_path: String,
    },

    /// An action was marked as completed.
    #[serde(rename = "action_completed")]
    ActionCompleted {
        /// Name of the completed action
        name: String,
        /// ISO 8601 timestamp when completion occurred
        completed_at: String,
    },

    /// An action was cancelled.
    #[serde(rename = "action_cancelled")]
    ActionCancelled {
        /// Name of the cancelled action
        name: String,
        /// Optional reason for cancellation
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },

    /// An action was started (moved to in_progress state).
    #[serde(rename = "action_started")]
    ActionStarted {
        /// Name of the started action
        name: String,
    },

    /// An action was blocked (moved to blocked/awaiting state).
    #[serde(rename = "action_blocked")]
    ActionBlocked {
        /// Name of the blocked action
        name: String,
        /// Optional reason for blocking
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },

    /// A completed action was restarted (moved back to not_started).
    #[serde(rename = "action_restarted")]
    ActionRestarted {
        /// Name of the restarted action
        name: String,
        /// Optional reason for restarting
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },

    /// An action was deleted from a file.
    #[serde(rename = "action_deleted")]
    ActionDeleted {
        /// Name of the deleted action
        name: String,
    },

    // =========================================================================
    // Property Change Events
    // =========================================================================
    /// An action's priority was changed.
    #[serde(rename = "priority_changed")]
    PriorityChanged {
        /// Previous priority value (None if unset)
        old_priority: Option<u32>,
        /// New priority value (None if cleared)
        new_priority: Option<u32>,
    },

    /// An action's due date was changed.
    #[serde(rename = "due_date_changed")]
    DueDateChanged {
        /// Previous due date (ISO 8601, None if unset)
        old_date: Option<String>,
        /// New due date (ISO 8601, None if cleared)
        new_date: Option<String>,
    },

    /// An action was renamed.
    #[serde(rename = "name_changed")]
    NameChanged {
        /// Previous name
        old_name: String,
        /// New name
        new_name: String,
    },

    /// A context tag was added to an action.
    #[serde(rename = "context_added")]
    ContextAdded {
        /// The context tag that was added
        context: String,
    },

    /// A context tag was removed from an action.
    #[serde(rename = "context_removed")]
    ContextRemoved {
        /// The context tag that was removed
        context: String,
    },

    // =========================================================================
    // Recurring Action Events
    // =========================================================================
    /// A new instance was generated from a recurring template.
    #[serde(rename = "instance_generated")]
    InstanceGenerated {
        /// UUID of the recurring template
        template_uuid: String,
        /// Date of the generated occurrence (ISO 8601)
        occurrence_date: String,
    },

    /// A recurring action instance was completed.
    #[serde(rename = "instance_completed")]
    InstanceCompleted {
        /// UUID of the recurring template
        template_uuid: String,
        /// Originally scheduled date (ISO 8601)
        scheduled_date: String,
        /// Actual completion date (ISO 8601)
        completed_date: String,
    },

    /// A recurring action occurrence was skipped.
    #[serde(rename = "instance_skipped")]
    InstanceSkipped {
        /// UUID of the recurring template
        template_uuid: String,
        /// Date of the skipped occurrence (ISO 8601)
        occurrence_date: String,
        /// Optional reason for skipping
        #[serde(skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },

    /// A recurring action template was edited.
    #[serde(rename = "template_edited")]
    TemplateEdited {
        /// UUID of the recurring template
        template_uuid: String,
        /// List of field names that were changed
        fields_changed: Vec<String>,
    },

    // =========================================================================
    // Sync Events
    // =========================================================================
    /// A sync operation started.
    #[serde(rename = "sync_started")]
    SyncStarted {
        /// Remote endpoint identifier
        remote: String,
        /// Direction: "push", "pull", or "bidirectional"
        direction: String,
    },

    /// A sync operation completed successfully.
    #[serde(rename = "sync_completed")]
    SyncCompleted {
        /// Remote endpoint identifier
        remote: String,
        /// Number of changes sent to remote
        changes_sent: u32,
        /// Number of changes received from remote
        changes_received: u32,
    },

    /// A sync operation failed.
    #[serde(rename = "sync_failed")]
    SyncFailed {
        /// Remote endpoint identifier
        remote: String,
        /// Error message describing the failure
        error: String,
    },

    /// A CRDT conflict was automatically resolved.
    #[serde(rename = "conflict_resolved")]
    ConflictResolved {
        /// UUID of the action with the conflict
        action_uuid: String,
        /// Description of how the conflict was resolved
        resolution: String,
    },

    // =========================================================================
    // System Events
    // =========================================================================
    /// A workspace was opened.
    #[serde(rename = "workspace_opened")]
    WorkspaceOpened {
        /// Path to the workspace root
        path: String,
        /// Number of actions loaded
        action_count: usize,
    },

    /// An actions file was parsed.
    #[serde(rename = "file_parsed")]
    FileParsed {
        /// Path to the parsed file
        file_path: String,
        /// Number of actions in the file
        action_count: usize,
        /// Time taken to parse in milliseconds
        parse_time_ms: u64,
    },

    /// The LSP server started.
    #[serde(rename = "lsp_started")]
    LspStarted {
        /// Port number if using TCP transport
        #[serde(skip_serializing_if = "Option::is_none")]
        port: Option<u16>,
    },
}

impl TelemetryEvent {
    /// Get the event type name for logging and filtering purposes.
    ///
    /// Returns the snake_case event name matching the JSON serialization.
    pub fn name(&self) -> &'static str {
        match self {
            TelemetryEvent::ActionCreated { .. } => "action_created",
            TelemetryEvent::ActionCompleted { .. } => "action_completed",
            TelemetryEvent::ActionCancelled { .. } => "action_cancelled",
            TelemetryEvent::ActionStarted { .. } => "action_started",
            TelemetryEvent::ActionBlocked { .. } => "action_blocked",
            TelemetryEvent::ActionRestarted { .. } => "action_restarted",
            TelemetryEvent::ActionDeleted { .. } => "action_deleted",
            TelemetryEvent::PriorityChanged { .. } => "priority_changed",
            TelemetryEvent::DueDateChanged { .. } => "due_date_changed",
            TelemetryEvent::NameChanged { .. } => "name_changed",
            TelemetryEvent::ContextAdded { .. } => "context_added",
            TelemetryEvent::ContextRemoved { .. } => "context_removed",
            TelemetryEvent::InstanceGenerated { .. } => "instance_generated",
            TelemetryEvent::InstanceCompleted { .. } => "instance_completed",
            TelemetryEvent::InstanceSkipped { .. } => "instance_skipped",
            TelemetryEvent::TemplateEdited { .. } => "template_edited",
            TelemetryEvent::SyncStarted { .. } => "sync_started",
            TelemetryEvent::SyncCompleted { .. } => "sync_completed",
            TelemetryEvent::SyncFailed { .. } => "sync_failed",
            TelemetryEvent::ConflictResolved { .. } => "conflict_resolved",
            TelemetryEvent::WorkspaceOpened { .. } => "workspace_opened",
            TelemetryEvent::FileParsed { .. } => "file_parsed",
            TelemetryEvent::LspStarted { .. } => "lsp_started",
        }
    }
}

/// A complete telemetry record ready for NDJSON serialization.
///
/// This is the envelope structure that wraps a [`TelemetryEvent`] with
/// common metadata fields (timestamp, tool, action_uuid).
///
/// # Serialization
///
/// The record is serialized as a flat JSON object with the event fields
/// merged in (via `#[serde(flatten)]`):
///
/// ```json
/// {
///   "timestamp": "2026-01-30T10:30:00+00:00",
///   "tool": "cli",
///   "action_uuid": "abc-123",
///   "event": "action_created",
///   "name": "My task",
///   "file_path": "inbox.actions"
/// }
/// ```
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct TelemetryRecord {
    /// ISO 8601 timestamp when the event occurred
    pub timestamp: String,
    /// Tool that generated this event
    pub tool: Tool,
    /// Related action UUID (if applicable)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_uuid: Option<String>,
    /// The semantic event data
    #[serde(flatten)]
    pub event: TelemetryEvent,
}

impl TelemetryRecord {
    /// Create a new telemetry record with the current UTC timestamp.
    ///
    /// # Arguments
    ///
    /// * `tool` - The tool generating this event
    /// * `action_uuid` - Optional UUID of the related action
    /// * `event` - The semantic event data
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// let record = TelemetryRecord::new(
    ///     Tool::Cli,
    ///     Some("abc-123".to_string()),
    ///     TelemetryEvent::ActionDeleted { name: "My task".to_string() },
    /// );
    /// ```
    pub fn new(tool: Tool, action_uuid: Option<String>, event: TelemetryEvent) -> Self {
        Self {
            timestamp: Utc::now().to_rfc3339(),
            tool,
            action_uuid,
            event,
        }
    }

    /// Create a new telemetry record with a specific timestamp.
    ///
    /// This is useful for backfilling historical events or preserving
    /// the original timestamp when an event is recorded after-the-fact.
    ///
    /// # Arguments
    ///
    /// * `timestamp` - The timestamp to use for this event
    /// * `tool` - The tool generating this event
    /// * `action_uuid` - Optional UUID of the related action
    /// * `event` - The semantic event data
    pub fn with_timestamp(
        timestamp: DateTime<Utc>,
        tool: Tool,
        action_uuid: Option<String>,
        event: TelemetryEvent,
    ) -> Self {
        Self {
            timestamp: timestamp.to_rfc3339(),
            tool,
            action_uuid,
            event,
        }
    }
}

/// Get the XDG state directory for ClearHead telemetry.
///
/// Returns the path where telemetry files are stored:
/// - **Linux:** `~/.local/state/clearhead/telemetry/` (or `$XDG_STATE_HOME/clearhead/telemetry/`)
/// - **macOS:** `~/Library/Application Support/clearhead/telemetry/`
/// - **Windows:** `%LOCALAPPDATA%\clearhead\state\telemetry\`
///
/// The directory is created automatically when events are emitted.
pub fn get_telemetry_dir() -> PathBuf {
    let state_dir = dirs::state_dir()
        .or_else(|| {
            // Fallback for systems without XDG_STATE_HOME
            dirs::data_local_dir().map(|p| p.join("state"))
        })
        .unwrap_or_else(|| {
            dirs::home_dir()
                .expect("Could not determine home directory")
                .join(".local")
                .join("state")
        });

    state_dir.join("clearhead").join("telemetry")
}

/// Get the current month's telemetry file path.
///
/// Files are named `events-YYYY-MM.ndjson` for monthly rotation.
fn get_current_file() -> PathBuf {
    let now = Utc::now();
    let filename = format!("events-{}.ndjson", now.format("%Y-%m"));
    get_telemetry_dir().join(filename)
}

/// Initialize the telemetry subsystem by ensuring the directory exists.
///
/// This is called automatically by [`emit`], but can be called explicitly
/// during application startup to fail fast if permissions are wrong.
///
/// # Errors
///
/// Returns an error if the directory cannot be created.
pub fn init() -> Result<(), String> {
    let dir = get_telemetry_dir();
    fs::create_dir_all(&dir).map_err(|e| format!("Failed to create telemetry directory: {}", e))
}

/// Emit a telemetry record to the NDJSON file.
///
/// This function:
/// 1. Ensures the telemetry directory exists
/// 2. Serializes the record to JSON
/// 3. Appends it to the current month's file
/// 4. Logs via tracing for operational visibility
///
/// # Arguments
///
/// * `record` - The complete telemetry record to emit
///
/// # Errors
///
/// Returns an error if:
/// - The telemetry directory cannot be created
/// - The record cannot be serialized
/// - The file cannot be written
///
/// # Example
///
/// ```rust,ignore
/// let record = TelemetryRecord::new(
///     Tool::Cli,
///     Some("abc-123".to_string()),
///     TelemetryEvent::ActionCreated {
///         name: "My task".to_string(),
///         file_path: "inbox.actions".to_string(),
///     },
/// );
/// emit(record)?;
/// ```
pub fn emit(record: TelemetryRecord) -> Result<(), String> {
    // Ensure directory exists
    init()?;

    // Serialize to JSON
    let json =
        serde_json::to_string(&record).map_err(|e| format!("Failed to serialize event: {}", e))?;

    // Append to file
    let file_path = get_current_file();
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(&file_path)
        .map_err(|e| format!("Failed to open telemetry file: {}", e))?;

    writeln!(file, "{}", json).map_err(|e| format!("Failed to write event: {}", e))?;

    // Also log for operational visibility (journald, stderr)
    info!(
        event = record.event.name(),
        action_uuid = ?record.action_uuid,
        tool = ?record.tool,
        "telemetry"
    );

    Ok(())
}

/// Convenience function to emit an event with the current timestamp.
///
/// This is the most common way to emit telemetry events. It automatically
/// creates a [`TelemetryRecord`] with the current UTC timestamp.
///
/// # Arguments
///
/// * `tool` - The tool generating this event (Cli, Lsp, or Sync)
/// * `action_uuid` - Optional UUID of the related action
/// * `event` - The semantic event to emit
///
/// # Errors
///
/// See [`emit`] for error conditions.
///
/// # Example
///
/// ```rust,ignore
/// // Emit when an action is completed
/// emit_event(
///     Tool::Cli,
///     Some(action.id.to_string()),
///     TelemetryEvent::ActionCompleted {
///         name: action.name.clone(),
///         completed_at: chrono::Utc::now().to_rfc3339(),
///     },
/// )?;
/// ```
pub fn emit_event(
    tool: Tool,
    action_uuid: Option<String>,
    event: TelemetryEvent,
) -> Result<(), String> {
    let record = TelemetryRecord::new(tool, action_uuid, event);
    emit(record)
}

// =============================================================================
// Conversion Helpers
// =============================================================================

/// Convert a [`FieldChange`] to a [`TelemetryEvent`], if applicable.
///
/// Returns `None` for field changes that don't have a corresponding telemetry event
/// (e.g., description changes, context changes that need special handling).
///
/// # Example
///
/// ```rust,ignore
/// use clearhead_cli::diff::FieldChange;
/// use clearhead_cli::telemetry::event_from_field_change;
///
/// let change = FieldChange::Priority { old: Some(2), new: Some(1) };
/// if let Some(event) = event_from_field_change(&change) {
///     emit_event(Tool::Cli, Some(action_id), event)?;
/// }
/// ```
pub fn event_from_field_change(change: &FieldChange) -> Option<TelemetryEvent> {
    match change {
        FieldChange::Name { old, new } => Some(TelemetryEvent::NameChanged {
            old_name: old.clone(),
            new_name: new.clone(),
        }),
        FieldChange::Priority { old, new } => Some(TelemetryEvent::PriorityChanged {
            old_priority: *old,
            new_priority: *new,
        }),
        FieldChange::DoDate { old, new } => Some(TelemetryEvent::DueDateChanged {
            old_date: old.clone(),
            new_date: new.clone(),
        }),
        // State changes are handled separately via event_from_state_change
        // to allow passing the action name
        FieldChange::State { .. } => None,
        // Other field changes not yet mapped to events
        _ => None,
    }
}

/// Convert an [`ActionState`] transition to a [`TelemetryEvent`], if applicable.
///
/// Returns `None` for state transitions that don't have semantic meaning
/// (e.g., NotStarted → NotStarted).
///
/// # Arguments
///
/// * `old` - The previous state
/// * `new` - The new state
/// * `name` - The action name (used in the event payload)
///
/// # Example
///
/// ```rust,ignore
/// use clearhead_cli::entities::ActionState;
/// use clearhead_cli::telemetry::event_from_state_change;
///
/// let event = event_from_state_change(
///     ActionState::NotStarted,
///     ActionState::Completed,
///     "My task",
/// );
/// ```
pub fn event_from_state_change(
    old: ActionState,
    new: ActionState,
    name: &str,
) -> Option<TelemetryEvent> {
    match (old, new) {
        // Completing an action
        (_, ActionState::Completed) => Some(TelemetryEvent::ActionCompleted {
            name: name.to_string(),
            completed_at: Utc::now().to_rfc3339(),
        }),
        // Starting an action
        (_, ActionState::InProgress) => Some(TelemetryEvent::ActionStarted {
            name: name.to_string(),
        }),
        // Blocking an action
        (_, ActionState::BlockedorAwaiting) => Some(TelemetryEvent::ActionBlocked {
            name: name.to_string(),
            reason: None,
        }),
        // Cancelling an action
        (_, ActionState::Cancelled) => Some(TelemetryEvent::ActionCancelled {
            name: name.to_string(),
            reason: None,
        }),
        // Restarting a completed action
        (ActionState::Completed, ActionState::NotStarted) => {
            Some(TelemetryEvent::ActionRestarted {
                name: name.to_string(),
                reason: None,
            })
        }
        // No semantic event for other transitions
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    // =========================================================================
    // Serialization Tests
    // =========================================================================

    #[test]
    fn test_serialize_action_created() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::ActionCreated {
                name: "Test action".to_string(),
                file_path: "inbox.actions".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"event\":\"action_created\""));
        assert!(json.contains("\"tool\":\"cli\""));
        assert!(json.contains("\"action_uuid\":\"abc-123\""));
        assert!(json.contains("\"name\":\"Test action\""));
        assert!(json.contains("\"file_path\":\"inbox.actions\""));
    }

    #[test]
    fn test_serialize_action_completed() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::ActionCompleted {
                name: "Test action".to_string(),
                completed_at: "2026-01-30T10:00:00Z".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"event\":\"action_completed\""));
        assert!(json.contains("\"completed_at\":\"2026-01-30T10:00:00Z\""));
    }

    #[test]
    fn test_serialize_priority_changed() {
        let record = TelemetryRecord::new(
            Tool::Lsp,
            Some("def-456".to_string()),
            TelemetryEvent::PriorityChanged {
                old_priority: Some(2),
                new_priority: Some(1),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"event\":\"priority_changed\""));
        assert!(json.contains("\"tool\":\"lsp\""));
        assert!(json.contains("\"old_priority\":2"));
        assert!(json.contains("\"new_priority\":1"));
    }

    #[test]
    fn test_serialize_name_changed() {
        let record = TelemetryRecord::new(
            Tool::Lsp,
            Some("abc-123".to_string()),
            TelemetryEvent::NameChanged {
                old_name: "Old name".to_string(),
                new_name: "New name".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"event\":\"name_changed\""));
        assert!(json.contains("\"old_name\":\"Old name\""));
        assert!(json.contains("\"new_name\":\"New name\""));
    }

    #[test]
    fn test_serialize_due_date_changed() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::DueDateChanged {
                old_date: Some("2026-01-15".to_string()),
                new_date: Some("2026-01-20".to_string()),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"event\":\"due_date_changed\""));
        assert!(json.contains("\"old_date\":\"2026-01-15\""));
        assert!(json.contains("\"new_date\":\"2026-01-20\""));
    }

    #[test]
    fn test_serialize_instance_completed() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("instance-123".to_string()),
            TelemetryEvent::InstanceCompleted {
                template_uuid: "template-456".to_string(),
                scheduled_date: "2026-01-30".to_string(),
                completed_date: "2026-01-30T10:30:00Z".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"event\":\"instance_completed\""));
        assert!(json.contains("\"template_uuid\":\"template-456\""));
        assert!(json.contains("\"scheduled_date\":\"2026-01-30\""));
    }

    #[test]
    fn test_serialize_sync_completed() {
        let record = TelemetryRecord::new(
            Tool::Sync,
            None,
            TelemetryEvent::SyncCompleted {
                remote: "server.example.com".to_string(),
                changes_sent: 5,
                changes_received: 3,
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"event\":\"sync_completed\""));
        assert!(json.contains("\"tool\":\"sync\""));
        assert!(json.contains("\"changes_sent\":5"));
        assert!(json.contains("\"changes_received\":3"));
    }

    #[test]
    fn test_serialize_optional_fields_omitted() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            None, // No action_uuid
            TelemetryEvent::LspStarted { port: None },
        );

        let json = serde_json::to_string(&record).unwrap();
        // action_uuid should not appear when None
        assert!(!json.contains("action_uuid"));
        // port should not appear when None
        assert!(!json.contains("port"));
    }

    #[test]
    fn test_serialize_optional_reason_present() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::ActionCancelled {
                name: "Test action".to_string(),
                reason: Some("No longer needed".to_string()),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"reason\":\"No longer needed\""));
    }

    #[test]
    fn test_serialize_optional_reason_absent() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::ActionCancelled {
                name: "Test action".to_string(),
                reason: None,
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(!json.contains("reason"));
    }

    // =========================================================================
    // Event Name Tests
    // =========================================================================

    #[test]
    fn test_event_name_lifecycle() {
        assert_eq!(
            TelemetryEvent::ActionCreated {
                name: "".to_string(),
                file_path: "".to_string()
            }
            .name(),
            "action_created"
        );
        assert_eq!(
            TelemetryEvent::ActionCompleted {
                name: "".to_string(),
                completed_at: "".to_string()
            }
            .name(),
            "action_completed"
        );
        assert_eq!(
            TelemetryEvent::ActionDeleted {
                name: "".to_string()
            }
            .name(),
            "action_deleted"
        );
        assert_eq!(
            TelemetryEvent::ActionStarted {
                name: "".to_string()
            }
            .name(),
            "action_started"
        );
    }

    #[test]
    fn test_event_name_property_changes() {
        assert_eq!(
            TelemetryEvent::PriorityChanged {
                old_priority: None,
                new_priority: None
            }
            .name(),
            "priority_changed"
        );
        assert_eq!(
            TelemetryEvent::NameChanged {
                old_name: "".to_string(),
                new_name: "".to_string()
            }
            .name(),
            "name_changed"
        );
        assert_eq!(
            TelemetryEvent::DueDateChanged {
                old_date: None,
                new_date: None
            }
            .name(),
            "due_date_changed"
        );
    }

    #[test]
    fn test_event_name_sync() {
        assert_eq!(
            TelemetryEvent::SyncStarted {
                remote: "".to_string(),
                direction: "".to_string()
            }
            .name(),
            "sync_started"
        );
        assert_eq!(
            TelemetryEvent::SyncCompleted {
                remote: "".to_string(),
                changes_sent: 0,
                changes_received: 0
            }
            .name(),
            "sync_completed"
        );
        assert_eq!(
            TelemetryEvent::SyncFailed {
                remote: "".to_string(),
                error: "".to_string()
            }
            .name(),
            "sync_failed"
        );
    }

    // =========================================================================
    // Tool Serialization Tests
    // =========================================================================

    #[test]
    fn test_tool_serialization() {
        assert_eq!(serde_json::to_string(&Tool::Cli).unwrap(), "\"cli\"");
        assert_eq!(serde_json::to_string(&Tool::Lsp).unwrap(), "\"lsp\"");
        assert_eq!(serde_json::to_string(&Tool::Sync).unwrap(), "\"sync\"");
    }

    // =========================================================================
    // Record Creation Tests
    // =========================================================================

    #[test]
    fn test_record_with_timestamp() {
        use chrono::TimeZone;
        let timestamp = Utc.with_ymd_and_hms(2026, 1, 15, 10, 30, 0).unwrap();

        let record = TelemetryRecord::with_timestamp(
            timestamp,
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::ActionCreated {
                name: "Test".to_string(),
                file_path: "test.actions".to_string(),
            },
        );

        assert!(record.timestamp.contains("2026-01-15"));
        assert!(record.timestamp.contains("10:30:00"));
    }

    // =========================================================================
    // File I/O Tests
    // =========================================================================

    #[test]
    fn test_emit_creates_file() {
        let temp_dir = TempDir::new().unwrap();
        let telemetry_dir = temp_dir.path().join("clearhead").join("telemetry");

        // Override the directory for testing by creating it manually
        fs::create_dir_all(&telemetry_dir).unwrap();

        // Note: This test verifies the serialization works; actual file writing
        // to the real telemetry directory is tested via integration tests.
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("test-uuid".to_string()),
            TelemetryEvent::ActionCreated {
                name: "Test action".to_string(),
                file_path: "test.actions".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.len() > 0);
        assert!(json.contains("test-uuid"));
    }

    // =========================================================================
    // Edge Case Tests
    // =========================================================================

    #[test]
    fn test_special_characters_in_name() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::ActionCreated {
                name: "Test \"quoted\" action with\nnewline".to_string(),
                file_path: "path/with spaces/file.actions".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        // Verify JSON escaping works
        assert!(json.contains("\\\"quoted\\\""));
        assert!(json.contains("\\n"));
    }

    #[test]
    fn test_empty_fields() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("".to_string()), // Empty but present
            TelemetryEvent::ActionCreated {
                name: "".to_string(),
                file_path: "".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        assert!(json.contains("\"action_uuid\":\"\""));
        assert!(json.contains("\"name\":\"\""));
    }

    #[test]
    fn test_unicode_in_name() {
        let record = TelemetryRecord::new(
            Tool::Cli,
            Some("abc-123".to_string()),
            TelemetryEvent::ActionCreated {
                name: "Task with emoji 🎉 and Japanese 日本語".to_string(),
                file_path: "inbox.actions".to_string(),
            },
        );

        let json = serde_json::to_string(&record).unwrap();
        // Verify unicode is preserved (not escaped)
        assert!(json.contains("🎉"));
        assert!(json.contains("日本語"));
    }

    // =========================================================================
    // Conversion Helper Tests
    // =========================================================================

    #[test]
    fn test_event_from_field_change_name() {
        let change = FieldChange::Name {
            old: "Old name".to_string(),
            new: "New name".to_string(),
        };

        let event = event_from_field_change(&change);
        assert!(event.is_some());

        match event.unwrap() {
            TelemetryEvent::NameChanged { old_name, new_name } => {
                assert_eq!(old_name, "Old name");
                assert_eq!(new_name, "New name");
            }
            _ => panic!("Expected NameChanged event"),
        }
    }

    #[test]
    fn test_event_from_field_change_priority() {
        let change = FieldChange::Priority {
            old: Some(2),
            new: Some(1),
        };

        let event = event_from_field_change(&change);
        assert!(event.is_some());

        match event.unwrap() {
            TelemetryEvent::PriorityChanged {
                old_priority,
                new_priority,
            } => {
                assert_eq!(old_priority, Some(2));
                assert_eq!(new_priority, Some(1));
            }
            _ => panic!("Expected PriorityChanged event"),
        }
    }

    #[test]
    fn test_event_from_field_change_do_date() {
        let change = FieldChange::DoDate {
            old: Some("2026-01-15".to_string()),
            new: Some("2026-01-20".to_string()),
        };

        let event = event_from_field_change(&change);
        assert!(event.is_some());

        match event.unwrap() {
            TelemetryEvent::DueDateChanged { old_date, new_date } => {
                assert_eq!(old_date, Some("2026-01-15".to_string()));
                assert_eq!(new_date, Some("2026-01-20".to_string()));
            }
            _ => panic!("Expected DueDateChanged event"),
        }
    }

    #[test]
    fn test_event_from_field_change_state_returns_none() {
        // State changes should return None - they're handled by event_from_state_change
        let change = FieldChange::State {
            old: ActionState::NotStarted,
            new: ActionState::Completed,
        };

        assert!(event_from_field_change(&change).is_none());
    }

    #[test]
    fn test_event_from_field_change_description_returns_none() {
        // Description changes don't have a corresponding event yet
        let change = FieldChange::Description {
            old: Some("Old desc".to_string()),
            new: Some("New desc".to_string()),
        };

        assert!(event_from_field_change(&change).is_none());
    }

    #[test]
    fn test_event_from_state_change_completed() {
        let event =
            event_from_state_change(ActionState::NotStarted, ActionState::Completed, "My task");

        assert!(event.is_some());
        match event.unwrap() {
            TelemetryEvent::ActionCompleted { name, .. } => {
                assert_eq!(name, "My task");
            }
            _ => panic!("Expected ActionCompleted event"),
        }
    }

    #[test]
    fn test_event_from_state_change_started() {
        let event =
            event_from_state_change(ActionState::NotStarted, ActionState::InProgress, "My task");

        assert!(event.is_some());
        match event.unwrap() {
            TelemetryEvent::ActionStarted { name } => {
                assert_eq!(name, "My task");
            }
            _ => panic!("Expected ActionStarted event"),
        }
    }

    #[test]
    fn test_event_from_state_change_blocked() {
        let event = event_from_state_change(
            ActionState::InProgress,
            ActionState::BlockedorAwaiting,
            "My task",
        );

        assert!(event.is_some());
        match event.unwrap() {
            TelemetryEvent::ActionBlocked { name, reason } => {
                assert_eq!(name, "My task");
                assert!(reason.is_none());
            }
            _ => panic!("Expected ActionBlocked event"),
        }
    }

    #[test]
    fn test_event_from_state_change_cancelled() {
        let event =
            event_from_state_change(ActionState::InProgress, ActionState::Cancelled, "My task");

        assert!(event.is_some());
        match event.unwrap() {
            TelemetryEvent::ActionCancelled { name, reason } => {
                assert_eq!(name, "My task");
                assert!(reason.is_none());
            }
            _ => panic!("Expected ActionCancelled event"),
        }
    }

    #[test]
    fn test_event_from_state_change_restarted() {
        let event =
            event_from_state_change(ActionState::Completed, ActionState::NotStarted, "My task");

        assert!(event.is_some());
        match event.unwrap() {
            TelemetryEvent::ActionRestarted { name, reason } => {
                assert_eq!(name, "My task");
                assert!(reason.is_none());
            }
            _ => panic!("Expected ActionRestarted event"),
        }
    }

    #[test]
    fn test_event_from_state_change_no_op() {
        // Same state → no event
        let event =
            event_from_state_change(ActionState::NotStarted, ActionState::NotStarted, "My task");

        assert!(event.is_none());
    }

    #[test]
    fn test_event_from_state_change_in_progress_to_not_started() {
        // Going back from InProgress to NotStarted isn't "restarted" (that's only from Completed)
        let event =
            event_from_state_change(ActionState::InProgress, ActionState::NotStarted, "My task");

        assert!(event.is_none());
    }
}
